#spring:
#  ldap:
#    password: mk@1234
#    username: lifengming
#    urls: ldap://10.10.11.10:389
#    base: OU=技术研发中心,OU=魔筷科技,DC=mokuai,DC=com
spring:
  ldap:
    urls: ldap://10.10.11.10
    base: OU=技术研发中心,OU=魔筷科技,DC=mokuai,DC=com
    username: lifengming@mockuai.com
    password: mk@1234
