nacos:
  config:
    server-addr: dev.nacos.mockuai.net:8848
    namespace: 8f25b9ae-53af-4502-92dc-79d9e386c343
    group: DEFAULT_GROUP
    data-id: dev.yaml
    username: mockuai
    password: nacos
    type: yaml
spring:
  application:
    name: test
