#服务端口
server:
  port: 8001
dubbo:
  #应用名字
  application:
    name: provider-server
  #注册中心地址
  registry:
    address: zookeeper://47.96.188.139:8001
  #哪些服务要注册
  scan:
    base-packages: com.lifengming.provider.service
